name: gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET Core Project
      run: dotnet publish khizooo/khizooo.csproj -c Release -o release --nologo

    # Ensure base-tag in index.html is /khizooo/
    - name: Ensure base-tag in index.html is /khizooo/
      run: sed -i 's|<base href="/[^"]*"|<base href="/khizooo/"|g' release/wwwroot/index.html

    # Add _redirects file for SPA routing
    - name: Add _redirects file for SPA routing
      run: echo '/*    /index.html   200' > release/wwwroot/_redirects

    # Add .nojekyll file to allow files/folders starting with underscore
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    # Copy index.html to 404.html for SPA fallback
    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # Deploy to gh-pages branch
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
        CLEAN: true
